// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABAeTdSKeD3f9iD7VEOJUa75Nm214A9BI',
    appId: '1:493173768303:web:627a883cb970fcc2634d9a',
    messagingSenderId: '493173768303',
    projectId: 'colorist-tyx',
    authDomain: 'colorist-tyx.firebaseapp.com',
    storageBucket: 'colorist-tyx.firebasestorage.app',
    measurementId: 'G-3NEQLBZXSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJf3cKjIEZvezIklZzs38i9jof6okJWQY',
    appId: '1:493173768303:android:b71dc561ba496a46634d9a',
    messagingSenderId: '493173768303',
    projectId: 'colorist-tyx',
    storageBucket: 'colorist-tyx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5bGPu3H4_WqZC7xdzFEMNcpIQnnwTpeQ',
    appId: '1:493173768303:ios:78da8e2202f579db634d9a',
    messagingSenderId: '493173768303',
    projectId: 'colorist-tyx',
    storageBucket: 'colorist-tyx.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5bGPu3H4_WqZC7xdzFEMNcpIQnnwTpeQ',
    appId: '1:493173768303:ios:78da8e2202f579db634d9a',
    messagingSenderId: '493173768303',
    projectId: 'colorist-tyx',
    storageBucket: 'colorist-tyx.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABAeTdSKeD3f9iD7VEOJUa75Nm214A9BI',
    appId: '1:493173768303:web:627a883cb970fcc2634d9a',
    messagingSenderId: '493173768303',
    projectId: 'colorist-tyx',
    authDomain: 'colorist-tyx.firebaseapp.com',
    storageBucket: 'colorist-tyx.firebasestorage.app',
    measurementId: 'G-3NEQLBZXSG',
  );
}
